# Generated by Django 5.1 on 2025-01-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('group_name_db', models.TextField()),
                ('monday', models.TextField()),
                ('tuesday', models.TextField()),
                ('wednesday', models.TextField()),
                ('thursday', models.TextField()),
                ('friday', models.TextField()),
                ('saturday', models.TextField()),
            ],
        ),
    ]
